//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMagazineProgramming.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SCategory()
        {
            this.Posts = new HashSet<Post>();
        }
    
        public int Id { get; set; }
        public string NameSCategory { get; set; }
        public string Descibe { get; set; }
        public int IdXCategory { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Post> Posts { get; set; }
        public virtual XCategory XCategory { get; set; }
    }
}
