//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMagazineProgramming.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Traffic
    {
        public int Id { get; set; }
        public Nullable<int> TotalPost { get; set; }
        public Nullable<int> TotalMember { get; set; }
        public Nullable<int> TotalView { get; set; }
        public Nullable<int> Rate { get; set; }
    }
}
