//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMagazineProgramming.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public XCategory()
        {
            this.SCategories = new HashSet<SCategory>();
        }
    
        public int Id { get; set; }
        public string NameXCategory { get; set; }
        public string Descibe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCategory> SCategories { get; set; }
    }
}
